import { type NextPage } from "next";
import Head from "next/head";
import { RaceCard } from "../../components/RaceCard";
import { matchUps } from "../submit-build";

const matchUpsObject = matchUps.map((matchUp) => {
  return {
    yourRace: matchUp.charAt(0) === "Z" ? "Zerg" : matchUp.charAt(0) === "P" ? "Protoss" : "Terran",
    opponentRace:
      matchUp.charAt(2) === "Z" ? "Zerg" : matchUp.charAt(2) === "P" ? "Protoss" : "Terran",
    matchup: matchUp.toLowerCase(),
  };
});

const Races: NextPage = () => {
  return (
    <>
      <Head>
        <title>Find a Build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center gap-16 text-black dark:bg-gray-800 dark:text-white">
        <h1 className="text-4xl">Select a Matchup</h1>
        <ul className="grid grid-cols-1 gap-10 md:grid-cols-2 lg:grid-cols-3">
          {matchUpsObject.map((matchup) => {
            return (
              <li key={matchup.matchup}>
                <RaceCard
                  href={`/matchups/${matchup.yourRace
                    .charAt(0)
                    .toLowerCase()}v${matchup.opponentRace.charAt(0).toLowerCase()}`}
                  yourRaceImgSrc={`/${matchup.yourRace.toLowerCase()}.jpeg`}
                  opponentRaceImgSrc={`/${matchup.opponentRace.toLowerCase()}.jpeg`}
                  matchupName={`${matchup.yourRace} vs ${matchup.opponentRace}`}
                />
              </li>
            );
          })}
        </ul>
      </main>
    </>
  );
};

export default Races;
