import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "../../../../../utils/api";

const MatchUps: NextPage = () => {
  const { raceName, opponentRace } = useRouter().query as {
    raceName: string;
    opponentRace: string;
  };

  const builds = api.builds.getBuildsByMatchup.useQuery({
    matchUp: `${raceName.toLowerCase().charAt(0)}v${opponentRace.toLowerCase().charAt(0)}`,
  });

  return (
    <>
      <Head>
        <title>MatchUps</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center gap-8 text-black dark:bg-gray-800 dark:text-white">
        <section className="flex flex-col gap-4 text-center">
          <h1>{raceName}</h1>
          <p>VS.</p>
          <p>{opponentRace}</p>
        </section>

        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Match Up</th>
              <th>Build</th>
            </tr>
          </thead>
          {builds.data?.map((build) => (
            <tr key={build.id}>
              <td>{build.id}</td>
              <td>{build.matchUp}</td>
              <td>{build.build}</td>
            </tr>
          ))}
        </table>
      </main>
    </>
  );
};

export default MatchUps;
