import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "../utils/api";

const Builds: NextPage = () => {
  const builds = api.builds.getBuilds.useQuery();

  return (
    <>
      <Head>
        <title>Builds</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center gap-8 bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <Link href="/">Go Back</Link>
        <h1>Builds</h1>

        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Match Up</th>
              <th>Build</th>
            </tr>
          </thead>
          {builds.data?.map((build) => (
            <tr key={build.id}>
              <td>{build.id}</td>
              <td>{build.matchUp}</td>
              <td>{build.build}</td>
            </tr>
          ))}
        </table>
      </main>
    </>
  );
};

export default Builds;
